name: Deploy para VPS
on:
  push:
    branches: 
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: repo checkout 
        uses: action/checkout@v1
      - name: deployment 
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SOURCE: "."
          REMOTE_HOST: ${{secrets.HOST}}
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
