name: Deploy
on:
  push:
    branches: 
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: SSH and Deploy
       uses: appleboy/ssh-action@master
       with:
         host: 181.215.134.40
         username: root
         key: ${{ secrets.PRIVATE_KEY }}
         script: | 
               cd ~/projects/LoginGeneric 
               ls -la 
               ssh-add ~/.ssh/github_hunterkoon
               git pull
               ls -la
               cp  ~/credentials/data-base/user.txt ~/projects/LoginGeneric/src/main/resources/etc/credentials/ 
               cp  ~/credentials/data-base/pass.txt ~/projects/LoginGeneric/src/main/resources/etc/credentials/ 
               docker compose up --build -d
               git reset --hard

