name: Deploy para VPS
on:
  push:
    branches: 
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host:  ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PASS }}
          source: "."
          target: "/projects/LoginGeneric"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:  ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PASS }}
          script: |
            cd /
            cd projects/LoginGeneric
            docker compose up --build -d
