name: Deploy
on:
  push:
    branches: 
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
    
     - name: SSH and Deploy
       uses: appleboy/ssh-action@master
       with:
         host: 181.215.134.40
         username: root
         key: ${{ secrets.PRIVATE_KEY }}
         script: | 
               cd / & 
               cd projects/LoginGeneric &
               ls -la &
               git pull & 
               docker compose up --build -d
