name: Deploy para VPS
on:
  push:
    branches: 
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: ls -all


      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host:  ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "/projects/LoginGeneric"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:  ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /
            cd projects/LoginGeneric &
            git pull &  
            docker compose up --build -d
